Repository ProjectSciFy/Storytime, pull requests merged in 2023-02, with the labels that each got.

#12 GP TEST: New settings -> main files manipulation
  UI.py
  hans_test.txt.txt
  sw_test.txt
Labels: test

#20 GP -> MAIN: Updated UI.py file, Created Colorscheme.txt file
  Colorschemes.txt
  UI.py
Labels: documentation, new feature, updating feature

#25 Update UI.py
  UI.py
Labels: bug, closed or ignore

#26 Updated UI.py and Dropdown.py
  UI.py
  dropdown.py
Labels: new feature

#27 Refactored UI.py
  UI.py
  dropdown.py
  generate.py
  helpers.py
  main.py
  story.py
  utility.py
Labels: documentation, updating feature

#28 added text box
  inputbox.py
  main.py
Labels: new feature

#29 ADD SOUNDS FOLDER
  sounds/temp.txt
Labels: new feature, help wanted

#31 ADDED: Sounds, Background gradient
  UI.py
  dropdown.py
  gradient.py
  helpers.py
  main.py
  sounds.py
  story.py
  utility.py
Labels: documentation, new feature, help wanted

#32 Added sound files
  sounds/Bubbles_Opening.wav
  sounds/ClingButton.wav
  sounds/SciFiButton.wav
  sounds/Success.wav
  sounds/temp.txt
Labels: documentation, new feature

#33 Update sounds.py -- FIXED: Spaces in path
  sounds.py
Labels: updating feature

#34 Update sounds.py
  sounds.py
Labels: updating feature

#38 Intro and logo added
  __pycache__/dropdown.cpython-37.pyc
  __pycache__/fadeIn.cpython-37.pyc
  __pycache__/fadeIn.cpython-38.pyc
  __pycache__/gradient.cpython-37.pyc
  __pycache__/helpers.cpython-37.pyc
  __pycache__/inputbox.cpython-37.pyc
  __pycache__/main.cpython-37.pyc
  __pycache__/sounds.cpython-37.pyc
  __pycache__/story.cpython-37.pyc
  __pycache__/story.cpython-38.pyc
  __pycache__/utility.cpython-37.pyc
  __pycache__/utility.cpython-38.pyc
  fadeIn.py
  story_time_logo.png
Labels: new feature, updating feature
